version: "3.9"
services:
    application:
        build:
            context: .
            dockerfile: Dockerfile.magikarp
        restart: unless-stopped
        ports: 
            - "80:80"
            - "9000:9000" # gotty port
        volumes:
            - "./docs:/root/docs"
        networks:
            pipe:
                ipv4_address: 10.5.0.2
    puppeteer:
        build:
            context: .
            dockerfile: Dockerfile.puppeteer
        restart: unless-stopped
        networks:
            pipe:
                ipv4_address: 10.5.0.10
    vim:
        build:
            context: .
            dockerfile: Dockerfile.vim
        restart: unless-stopped
        volumes:
            - "./editor:/root/editor"
        extra_hosts:
                - "magikarp.sale:10.5.0.2"
        networks:
            pipe:
                ipv4_address: 10.5.0.20
networks:
    pipe:
        ipam:
            config:
                - subnet: 10.5.0.0/16
