import { api_pipeserver_v0_3 } from "./api/api_v0_3.ts";
import {
  getCommandLineArgs,
  PipeFunctions,
  processPipeMessages,
} from "./common.ts";

const args = getCommandLineArgs({
  // animated icon, doesn't work on chrome
  favicon:
    `R0lGODlhEAAQAPIAAAAAAFRUVF5eXqCiowAAAAAAAAAAAAAAACH5BAkUAAQAIf8LTkVUU0NBUEUyLjADAQAAACwAAAAAEAAQAAAD6khERESEEEIIIYQQQgghBEEQBEEQBCEIgiAQBEEQBEEQBCEMwyAQBAKBQCAQCASCYDAYCAKBQCAQCAQCAYJgMBgMBoPBYDAYDAYDgmAwGAwGg8FgMBgMBgOCYDAYDAYDAwMDAwMDAwMEAgMDAwMDAwMDAwMDAwMDBAIDAwMDAwMDAwMDAwMDAwQCAwMDAwMDAwMDAwMDAwMEAgMDAwIBAQEBAQEBAQEBBAIDAwMCBAQEBAQEBAQEBAQCAgICAgQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIECBAgAABAgQSAAAh+QQJFAADACwAAAAAEAAQAIEAAABUVFSgoqMAAAAC59w2MzMzM8YYY4wxxhhjjDEMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAYDAaDQCAQCAQCgUAgEAgEAgGBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAQEBAQEBAQEBAQEBAQEBAQMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYMCAAQMKAAAh+QQJFAADACwAAAAAEAAQAIEAAABUVFSgoqMAAAAC59w2MzMzM8YYY4wxxhhjjDEMwzAMwzAMwzAMQxAEQTAMwzAMwzAMQyAQCAKDQCAQCAQCgUAgIBAIAgOBQCAQCAQCgUAgEAgCA4FAIBAIBAKBQCAQCAIDgUAgEAgEAoFAICAgEDAgICAgICAgICAgICAgIBAwICAgICAgICAgICAgICAQMCAgICAgICAgICAgICAgEDAQEBAQEBAQEBAQECAgIBAwMDAwMDAwMDAwMBAgICAQMDAwMDAwMDAwMDAQEBAQEDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYMCAAQMKAAAh+QQJFAADACwAAAAAEAAQAIEAAABUVFSgoqMAAAAC59w2MzMzM8YYY4wxxhhjjDEMwzAMwxAEQRAMQRAEwTAMwxAIghAMgSAQBAaDQCAQEAgEgUFAIBAEAgGBQCAQCASBQUAgEAgEAoFAIBAIBIFBQCAQCAQCgUAgEAgEgUFAICAgICAgICAgICAgEDAQICAgICAgICAgICAgIBAwECAgICAgICAgICAgICAQMBAgICAgICAQEBAQICAgEDAQICAgEBAQMDAwECAgIBAwECAgIBAwMDAwMBAQEBAQMBAQEBAQMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYMCAAQMKAAA7`,
  base64encoded: true,
});

const filterMessages = async (
  message: api_pipeserver_v0_3,
  pipe: PipeFunctions,
) => {
  if (message.request.url === "/favicon.ico") {
    pipe.debug("Sending favicon");
    message.reply.returnCode = 200;
    message.reply.headers["Content-Type"] = "image/x-icon";
    message.reply.type = "base64";
    message.reply.body = args.favicon;
  }

  return message;
};

processPipeMessages<api_pipeserver_v0_3>(
  filterMessages,
  "Started favicon app...",
);

// vim: ts=2 sts=2 sw=2 tw=0 noet
