import {
  getCommandLineArgs,
  PipeFunctions,
  PipeServerAPIv03,
  processPipeMessages,
} from "../dependencies.ts";

const args = getCommandLineArgs({
  // animated icon, doesn't work on chrome
  favicon:
    `R0lGODlhEAAQAPIAAAAAAFRUVF5eXqCiowAAAAAAAAAAAAAAACH5BAkUAAQAIf8LTkVUU0NBUEUyLjADAQAAACwAAAAAEAAQAAAD6khERESEEEIIIYQQQgghBEEQBEEQBCEIgiAQBEEQBEEQBCEMwyAQBAKBQCAQCASCYDAYCAKBQCAQCAQCAYJgMBgMBoPBYDAYDAYDgmAwGAwGg8FgMBgMBgOCYDAYDAYDAwMDAwMDAwMEAgMDAwMDAwMDAwMDAwMDBAIDAwMDAwMDAwMDAwMDAwQCAwMDAwMDAwMDAwMDAwMEAgMDAwIBAQEBAQEBAQEBBAIDAwMCBAQEBAQEBAQEBAQCAgICAgQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIECBAgAABAgQSAAAh+QQJFAADACwAAAAAEAAQAIEAAABUVFSgoqMAAAAC59w2MzMzM8YYY4wxxhhjjDEMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAYDAaDQCAQCAQCgUAgEAgEAgGBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAQEBAQEBAQEBAQEBAQEBAQMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYMCAAQMKAAAh+QQJFAADACwAAAAAEAAQAIEAAABUVFSgoqMAAAAC59w2MzMzM8YYY4wxxhhjjDEMwzAMwzAMwzAMQxAEQTAMwzAMwzAMQyAQCAKDQCAQCAQCgUAgIBAIAgOBQCAQCAQCgUAgEAgCA4FAIBAIBAKBQCAQCAIDgUAgEAgEAoFAICAgEDAgICAgICAgICAgICAgIBAwICAgICAgICAgICAgICAQMCAgICAgICAgICAgICAgEDAQEBAQEBAQEBAQECAgIBAwMDAwMDAwMDAwMBAgICAQMDAwMDAwMDAwMDAQEBAQEDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYMCAAQMKAAAh+QQJFAADACwAAAAAEAAQAIEAAABUVFSgoqMAAAAC59w2MzMzM8YYY4wxxhhjjDEMwzAMwxAEQRAMQRAEwTAMwxAIghAMgSAQBAaDQCAQEAgEgUFAIBAEAgGBQCAQCASBQUAgEAgEAoFAIBAIBIFBQCAQCAQCgUAgEAgEgUFAICAgICAgICAgICAgEDAQICAgICAgICAgICAgIBAwECAgICAgICAgICAgICAQMBAgICAgICAQEBAQICAgEDAQICAgEBAQMDAwECAgIBAwECAgIBAwMDAwMBAQEBAQMBAQEBAQMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYMCAAQMKAAA7`,
  base64encoded: true,
});

const filterMessages = (
  message: PipeServerAPIv03,
  pipe: PipeFunctions,
) => {
  if (message.request.url === "/favicon.ico") {
    pipe.debug("Sending favicon");
    message.reply.returnCode = 200;
    message.reply.headers["Content-Type"] = "image/x-icon";
    message.reply.type = "base64";
    message.reply.body = args.favicon;
  }

  return message;
};

processPipeMessages<PipeServerAPIv03>(
  filterMessages,
  "favicon",
);

// vim: ts=2 sts=2 sw=2 tw=0 noet
