FROM golang

WORKDIR /root
RUN git clone https://github.com/kkdai/youtube.git && cd youtube && go build -o /root/youtubedr ./cmd/youtubedr
RUN wget https://github.com/sorenisanerd/gotty/releases/download/v1.5.0/gotty_v1.5.0_linux_amd64.tar.gz && tar -xvf gotty_v1.5.0_linux_amd64.tar.gz