FROM denoland/deno:1.20.5 as runner

WORKDIR /root

COPY --from=pipe-webserver/build /root/receiver.js receiver.js
COPY --from=pipe-webserver/build /root/emmiter.js emmiter.js
COPY --from=pipe-webserver/build /root/filter.js filter.js

RUN deno install --allow-net=:8000 /root/receiver.js
RUN deno install /root/filter.js
RUN deno install --allow-net=localhost:8000 /root/emmiter.js

EXPOSE 8000
ENTRYPOINT [ "/bin/bash" , "-eo", "pipefail", "-c"]
CMD [" receiver | filter | emmiter "]
