# syntax=docker/dockerfile:1.3
FROM denoland/deno:1.31.1

COPY ./ /root/
WORKDIR /root
RUN --mount=type=cache,target=/deno-dir deno cache src/dependencies.ts
RUN deno lint
RUN deno fmt --check
RUN --mount=type=cache,target=/deno-dir deno task bundle-all
WORKDIR /root/build
RUN ls -1 *.ts.bundle | sed 'p;s/\.ts.bundle/\.js/' | xargs -n2 mv